#!/usr/bin/env bash

# Shared adapter helpers. Source from per-adapter build scripts.

TIER0_RULE_IDS="no-hardcoded-secrets prompt-injection-prevention agentic-human-approval ai-audit-logging mcp-server-safety"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found on PATH: $1"
}

require_yq() {
  if command -v yq >/dev/null 2>&1; then
    yq --version >/dev/null 2>&1 || die "Unable to execute yq"
  fi
}

require_yaml_reader() {
  # yq is preferred when available. The awk fallback covers the scalar fields
  # and simple arrays used by the registry schemas without adding dependencies.
  require_command awk
}

is_tier0_rule() {
  case " $TIER0_RULE_IDS " in
    *" $1 "*) return 0 ;;
    *) return 1 ;;
  esac
}

adapter_version() {
  if [ -n "${SECUREAI_LIBRARY_VERSION:-}" ]; then
    printf '%s' "$SECUREAI_LIBRARY_VERSION"
    return
  fi

  git -C "$LIB_ROOT" describe --tags --abbrev=0 2>/dev/null || printf 'v0.0.0-dev'
}

registry_sha() {
  git -C "$LIB_ROOT" rev-parse --short HEAD 2>/dev/null || printf 'unknown'
}

generated_header() {
  printf '# Generated by SecureAICodeLibrary adapter %s from registry@%s\n' "$(adapter_version)" "$(registry_sha)"
}

yaml_scalar() {
  file=$1
  expr=$2
  if command -v yq >/dev/null 2>&1; then
    value=$(yq e -r "$expr // \"\"" "$file")
  else
    value=$(yaml_scalar_awk "$file" "$expr")
  fi
  if [ "$value" = "null" ]; then
    value=""
  fi
  printf '%s' "$value"
}

yaml_array_lines() {
  file=$1
  expr=$2
  if command -v yq >/dev/null 2>&1; then
    yq e -r "$expr[]?" "$file"
  else
    yaml_array_lines_awk "$file" "$expr"
  fi
}

yaml_scalar_awk() {
  file=$1
  expr=$2
  awk -v expr="$expr" '
    BEGIN {
      gsub(/^\./, "", expr)
      n = split(expr, path, ".")
    }
    function clean(value) {
      sub(/^[[:space:]]*/, "", value)
      sub(/[[:space:]]*$/, "", value)
      if (value == "null") {
        value = ""
      }
      if ((value ~ /^".*"$/) || (value ~ /^'\''.*'\''$/)) {
        value = substr(value, 2, length(value) - 2)
      }
      gsub(/\\"/, "\"", value)
      return value
    }
    function path_matches(level, key, i) {
      if (level != n - 1 || key != path[n]) {
        return 0
      }
      for (i = 1; i < n; i++) {
        if (stack[i - 1] != path[i]) {
          return 0
        }
      }
      return 1
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      raw = $0
      indent = raw
      sub(/[^ ].*$/, "", indent)
      level = int(length(indent) / 2)
      line = raw
      sub(/^[[:space:]]*/, "", line)
      if (line ~ /^[A-Za-z0-9_-]+:[[:space:]]*/) {
        key = line
        sub(/:.*/, "", key)
        value = line
        sub(/^[^:]*:[[:space:]]*/, "", value)
        stack[level] = key
        for (i = level + 1; i < 20; i++) {
          delete stack[i]
        }
        if (path_matches(level, key)) {
          print clean(value)
          exit
        }
      }
    }
  ' "$file"
}

yaml_array_lines_awk() {
  file=$1
  expr=$2
  awk -v expr="$expr" '
    BEGIN {
      gsub(/^\./, "", expr)
      sub(/\[\?\]$/, "", expr)
      n = split(expr, path, ".")
      in_array = 0
    }
    function clean(value) {
      sub(/^[[:space:]]*/, "", value)
      sub(/[[:space:]]*$/, "", value)
      gsub(/^,/, "", value)
      gsub(/,$/, "", value)
      sub(/^[[:space:]]*/, "", value)
      sub(/[[:space:]]*$/, "", value)
      if ((value ~ /^".*"$/) || (value ~ /^'\''.*'\''$/)) {
        value = substr(value, 2, length(value) - 2)
      }
      gsub(/\\"/, "\"", value)
      return value
    }
    function path_matches(level, key, i) {
      if (level != n - 1 || key != path[n]) {
        return 0
      }
      for (i = 1; i < n; i++) {
        if (stack[i - 1] != path[i]) {
          return 0
        }
      }
      return 1
    }
    function emit_inline_array(value, item_count, items, i) {
      gsub(/^\[/, "", value)
      gsub(/\]$/, "", value)
      item_count = split(value, items, ",")
      for (i = 1; i <= item_count; i++) {
        item = clean(items[i])
        if (item != "") {
          print item
        }
      }
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      raw = $0
      indent = raw
      sub(/[^ ].*$/, "", indent)
      level = int(length(indent) / 2)
      line = raw
      sub(/^[[:space:]]*/, "", line)

      if (in_array && level <= array_level && line !~ /^-/) {
        in_array = 0
      }
      if (in_array && line ~ /^-[[:space:]]*/) {
        item = line
        sub(/^-[[:space:]]*/, "", item)
        item = clean(item)
        if (item != "") {
          print item
        }
        next
      }

      if (line ~ /^[A-Za-z0-9_-]+:[[:space:]]*/) {
        key = line
        sub(/:.*/, "", key)
        value = line
        sub(/^[^:]*:[[:space:]]*/, "", value)
        stack[level] = key
        for (i = level + 1; i < 20; i++) {
          delete stack[i]
        }
        if (path_matches(level, key)) {
          if (value ~ /^\[.*\]$/) {
            emit_inline_array(value)
            exit
          }
          in_array = 1
          array_level = level
          next
        }
      }
    }
  ' "$file"
}

rule_id_for_file() {
  file=$1
  id=$(yaml_scalar "$file" '.metadata.id')
  if [ -z "$id" ]; then
    id=$(basename "$file" .rule.yaml)
  fi
  printf '%s' "$id"
}

rule_category_for_file() {
  file=$1
  rel=${file#"$RULES_ROOT"/}
  category=${rel%/*}
  if [ "$category" = "$rel" ]; then
    category=""
  fi
  printf '%s' "$category"
}

rule_relpath_for_file() {
  file=$1
  printf '%s' "${file#"$LIB_ROOT"/}"
}

collect_rule_records() {
  rules_root=$1
  records_file=$2

  [ -d "$rules_root" ] || die "Rules directory not found: $rules_root"
  : > "$records_file"

  while IFS= read -r rule_file; do
    [ -n "$rule_file" ] || continue
    id=$(rule_id_for_file "$rule_file")
    category=$(rule_category_for_file "$rule_file")
    [ -n "$id" ] || die "Rule file missing metadata.id: $rule_file"
    printf '%s\t%s\t%s\n' "$category" "$id" "$rule_file" >> "$records_file"
  done <<EOF
$(find "$rules_root" -type f -name '*.rule.yaml' | sort)
EOF

  [ -s "$records_file" ] || die "No rule files found under $rules_root"
  sorted_file=$(mktemp)
  sort -t "$(printf '\t')" -k1,1 -k2,2 "$records_file" > "$sorted_file"
  mv "$sorted_file" "$records_file"
}

validate_tier0_present() {
  records_file=$1
  for tier0_id in $TIER0_RULE_IDS; do
    if ! awk -F '\t' -v id="$tier0_id" '$2 == id { found = 1 } END { exit found ? 0 : 1 }' "$records_file"; then
      die "Required Tier 0 rule is missing from registry: $tier0_id"
    fi
  done
}

protects_regeneration() {
  target=$1
  [ -f "$target" ] || return 1
  IFS= read -r first_line < "$target" || first_line=""
  [ "$first_line" = "# DO NOT REGENERATE" ]
}

write_generated_file() {
  target=$1
  source_file=$2
  mode=${ADAPTER_MODE:-write}

  if protects_regeneration "$target"; then
    die "Refusing to overwrite protected file: $target"
  fi

  case "$mode" in
    dry-run)
      printf 'DRY-RUN would write %s\n' "$target"
      ;;
    check)
      if [ ! -f "$target" ]; then
        printf 'CHECK missing %s\n' "$target" >&2
        return 1
      fi
      if ! cmp -s "$source_file" "$target"; then
        printf 'CHECK drift %s\n' "$target" >&2
        return 1
      fi
      printf 'CHECK ok %s\n' "$target"
      ;;
    write)
      mkdir -p "$(dirname "$target")"
      cp "$source_file" "$target"
      printf 'WROTE %s\n' "$target"
      ;;
    *)
      die "Unknown adapter mode: $mode"
      ;;
  esac
}

escape_table_cell() {
  value=$1
  value=${value//$'\n'/ }
  value=${value//|/\\|}
  printf '%s' "$value"
}

join_lines_csv() {
  first=1
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    if [ "$first" -eq 1 ]; then
      printf '%s' "$line"
      first=0
    else
      printf ', %s' "$line"
    fi
  done
}

emit_subagents_none_if_absent() {
  subagents_root=$1
  if [ ! -d "$subagents_root" ] || [ -z "$(find "$subagents_root" -type f -name subagent.yaml -print -quit)" ]; then
    printf '## Subagents: (none registered yet)\n'
    return 0
  fi
  return 1
}
