#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

VERSION="1.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENV_DIR="${REPO_ROOT}/.venv"

usage() {
  cat <<'EOF'
Usage: scripts/build-index.sh [--help] [--version]

Regenerate registry/INDEX.md from registry/rules/**/*.rule.yaml.
Rows are sorted by (category, id) for cache stability.
EOF
}

case "${1:-}" in
  --help|-h) usage; exit 0 ;;
  --version) printf '%s\n' "${VERSION}"; exit 0 ;;
  "") ;;
  *) printf 'build-index.sh: unknown argument: %s\n' "$1" >&2; exit 2 ;;
esac

require_tool() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'build-index.sh: required tool not found: %s\n' "$1" >&2
    exit 1
  }
}

require_tool python3
require_tool git

if [[ ! -x "${VENV_DIR}/bin/python" ]]; then
  python3 -m venv "${VENV_DIR}"
fi

"${VENV_DIR}/bin/python" - <<'PY'
import importlib.util
import subprocess
import sys

if importlib.util.find_spec("yaml") is None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "PyYAML"])
PY

cd "${REPO_ROOT}"

"${VENV_DIR}/bin/python" - <<'PY'
from collections import Counter
from pathlib import Path
import subprocess

import yaml

ROOT = Path.cwd()
INDEX = ROOT / "registry/INDEX.md"

def git_sha():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"

def truncate(text, limit=80):
    text = " ".join(str(text or "").split())
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 3)].rstrip() + "..."

def md_escape(text):
    return str(text).replace("|", "\\|").replace("\n", " ")

rows = []
for path in sorted(ROOT.glob("registry/rules/**/*.rule.yaml")):
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    metadata = data.get("metadata") or {}
    rule_id = metadata.get("id") or path.name.removesuffix(".rule.yaml")
    category = data.get("category") or path.parent.name
    rows.append({
        "id": rule_id,
        "category": category,
        "severity": data.get("severity", "info"),
        "summary": data.get("summary", ""),
        "path": path.relative_to(ROOT).as_posix(),
    })

rows.sort(key=lambda row: (row["category"], row["id"]))
counts = Counter(row["category"] for row in rows)
summary_chars = sum(len(" ".join(str(row["summary"]).split())) for row in rows)
token_estimate = round(summary_chars / 4)

lines = [
    f"<!-- AUTO-GENERATED by 'make index'. Do not edit by hand. Last regen: {git_sha()} -->",
    "",
    "# Registry Index",
    "",
    "| ID | Category | Severity | Summary | Path |",
    "|---|---|---|---|---|",
]

for row in rows:
    lines.append(
        "| {id} | {category} | {severity} | {summary} | `{path}` |".format(
            id=md_escape(row["id"]),
            category=md_escape(row["category"]),
            severity=md_escape(row["severity"]),
            summary=md_escape(truncate(row["summary"], 80)),
            path=md_escape(row["path"]),
        )
    )

lines.extend(["", "## Counts", ""])
if counts:
    for category in sorted(counts):
        lines.append(f"- `{category}`: {counts[category]}")
else:
    lines.append("- No rules found.")
lines.append(f"- `total`: {len(rows)}")
lines.append(f"- `summary_token_estimate`: ~{token_estimate} tokens (4 chars/token, summaries only)")
lines.append("")

INDEX.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {INDEX.relative_to(ROOT)} with {len(rows)} rule(s).")
PY
